"""
PDF Report Generator
Generates professional disease detection report PDFs.
"""
import os
from datetime import datetime
from fpdf import FPDF

class ReportPDF(FPDF):
    def header(self):
        # Premium Header
        self.set_fill_color(240, 244, 255)
        self.rect(0, 0, 210, 40, "F")
        self.set_font("Helvetica", "B", 24)
        self.set_text_color(108, 99, 255)
        self.set_y(15)
        self.cell(0, 10, "MedDetect AI", new_x="LMARGIN", new_y="NEXT", align="C")
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(120, 120, 130)
        self.cell(0, 6, "CONFIDENTIAL  -  AI-ASSISTED HEALTH ANALYSIS", new_x="LMARGIN", new_y="NEXT", align="C")
        self.ln(15)

    def footer(self):
        self.set_y(-20)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(180, 180, 180)
        self.line(10, 277, 200, 277)
        self.cell(0, 10, f"Page {self.page_no()} of {{nb}}  |  Generated by MedDetect AI", align="C")

def generate_report(user_name, user_email, symptoms, predictions, disease_info_map, user_age="Unspecified"):
    """Generate professional PDF report and return bytes."""
    pdf = ReportPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    now = datetime.now().strftime("%B %d, %Y  %I:%M %p")

    # Patient Information Block
    pdf.set_fill_color(250, 250, 250)
    pdf.rect(10, 50, 190, 35, "F")
    pdf.set_draw_color(220, 220, 220)
    pdf.rect(10, 50, 190, 35, "D")
    
    pdf.set_y(52)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 8, "  PATIENT INFORMATION", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(80, 80, 80)
    # Row 1
    pdf.set_x(15)
    pdf.cell(60, 6, f"Name: {user_name}", align="L")
    pdf.cell(70, 6, f"Email: {user_email}", align="L")
    pdf.cell(50, 6, f"Age: {user_age}", align="L", new_x="LMARGIN", new_y="NEXT")
    # Row 2
    pdf.set_x(15)
    pdf.cell(130, 6, f"Report ID: MD-{datetime.now().strftime('%Y%m%d-%H%M')}", align="L")
    pdf.cell(50, 6, f"Date: {now}", align="L", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(12)

    # Primary Diagnosis Section
    if predictions:
        top_pred = predictions[0]
        top_info = disease_info_map.get(top_pred["disease"], {})
        severity = top_info.get("severity", "moderate").lower()
        
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(40, 40, 40)
        pdf.cell(0, 10, "PRIMARY AI PREDICTION", new_x="LMARGIN", new_y="NEXT")
        
        # Color coding for severity
        if severity in ["critical", "high"]:
            pdf.set_fill_color(255, 235, 238) # Light red
            pdf.set_draw_color(255, 138, 128)
            pdf.set_text_color(183, 28, 28)
        else:
            pdf.set_fill_color(240, 248, 255) # Light blue
            pdf.set_draw_color(140, 158, 255)
            pdf.set_text_color(40, 53, 147)
            
        pdf.set_font("Helvetica", "B", 16)
        pdf.cell(140, 12, f" {top_pred['disease']}", border=1, fill=True, align="L")
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(50, 12, f" Match: {top_pred['confidence']}% ", border=1, fill=True, align="R", new_x="LMARGIN", new_y="NEXT")
        
        # Warning if critical
        if severity in ["critical", "high"]:
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(211, 47, 47)
            pdf.ln(2)
            pdf.cell(0, 6, "  [URGENT] High/Critical severity detected. Immediate medical consultation is strongly advised.", new_x="LMARGIN", new_y="NEXT")
        
        # Add Doctor Locator Link
        specialist = top_info.get("specialist", "General Physician")
        search_query = f"{specialist} near me".replace(" ", "+")
        maps_url = f"https://www.google.com/maps/search/{search_query}"
        
        pdf.ln(3)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(0, 102, 204) # Classic Blue for Links
        pdf.cell(0, 6, f"  [FIND DOCTOR] Click here to search for a {specialist} near you on Google Maps", link=maps_url, new_x="LMARGIN", new_y="NEXT")
        
        # --- NEW REAL-WORLD DOCTOR RESOLVER ---
        try:
            from modules.doctor_locator import get_nearest_doctors
            doc_data = get_nearest_doctors(specialist)
            if doc_data and "doctors" in doc_data:
                pdf.ln(3)
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(60, 60, 60)
                pdf.cell(0, 6, f"  Nearest AI-Located {specialist}s in/around {doc_data['city']}:", new_x="LMARGIN", new_y="NEXT")
                
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(100, 100, 100)
                for idx, doctor in enumerate(doc_data["doctors"]):
                    d_name = doctor.get("name", "Unknown Clinic").encode('latin-1', 'replace').decode('latin-1')
                    d_phone = doctor.get("phone", "N/A").encode('latin-1', 'replace').decode('latin-1')
                    d_addr = doctor.get("address", "N/A").encode('latin-1', 'replace').decode('latin-1')
                    
                    pdf.set_font("Helvetica", "B", 9)
                    pdf.cell(0, 5, f"   {idx+1}) {d_name}", new_x="LMARGIN", new_y="NEXT")
                    pdf.set_font("Helvetica", "", 8)
                    pdf.cell(0, 5, f"       Phone: {d_phone}   |   Location: {d_addr}", new_x="LMARGIN", new_y="NEXT")
        except Exception as e:
            print(f"Error fetching doctors for PDF: {e}")
            
        pdf.ln(8)

    # Symptoms Reported
    pdf.set_text_color(40, 40, 40)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "REPORTED SYMPTOMS", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(80, 80, 80)
    symptoms_text = ", ".join([s.replace("_", " ").title() for s in symptoms])
    pdf.multi_cell(0, 6, symptoms_text)
    pdf.ln(8)

    # Further analysis
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(40, 40, 40)
    pdf.cell(0, 8, "DETAILED ANALYSIS", new_x="LMARGIN", new_y="NEXT")
    
    for i, p in enumerate(predictions):
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(108, 99, 255) if i == 0 else pdf.set_text_color(80, 80, 80)
        pdf.cell(0, 8, f"{i+1}. {p['disease']} (Confidence: {p['confidence']}%)", new_x="LMARGIN", new_y="NEXT")
        
        info = disease_info_map.get(p["disease"], {})
        if info:
            if info.get("specialist"):
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(0, 150, 136) # Green
                pdf.cell(0, 6, f"   Recommended Specialist: {info['specialist']}", new_x="LMARGIN", new_y="NEXT")
            
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(100, 100, 100)
            if info.get("description"):
                pdf.set_x(15)
                pdf.multi_cell(0, 5, f"{info['description']}")
                pdf.ln(2)
            
            # Print precautions
            if info.get("precautions"):
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_x(15)
                pdf.cell(0, 6, "Precautions:", new_x="LMARGIN", new_y="NEXT")
                pdf.set_font("Helvetica", "", 9)
                for prec in info["precautions"]:
                    pdf.set_x(20)
                    pdf.cell(0, 5, f"- {prec}", new_x="LMARGIN", new_y="NEXT")
            
            # Print home remedies
            if info.get("home_remedies"):
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_x(15)
                pdf.cell(0, 6, "Home Remedies/Care:", new_x="LMARGIN", new_y="NEXT")
                pdf.set_font("Helvetica", "", 9)
                for rem in info["home_remedies"]:
                    pdf.set_x(20)
                    pdf.cell(0, 5, f"- {rem}", new_x="LMARGIN", new_y="NEXT")
            pdf.ln(4)

    # Disclaimer
    pdf.ln(10)
    pdf.set_fill_color(255, 243, 224) # Warning yellow
    pdf.rect(10, pdf.get_y(), 190, 15, "F")
    pdf.set_y(pdf.get_y() + 2)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(230, 81, 0)
    pdf.set_x(15)
    pdf.cell(0, 5, "MEDICAL DISCLAIMER", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 8)
    pdf.set_x(15)
    pdf.multi_cell(180, 4, "This report is generated by a statistical AI model for informational and educational purposes only. It is NOT a clinical diagnosis. You must consult a licensed medical professional or physician for any health and medical advice.")
    
    return bytes(pdf.output())
