"""
Dataset Generator for Multi-Disease Detection System
Generates a large-scale symptom-disease dataset with ~773 diseases and ~377 symptoms.
"""
import csv, json, random, os

random.seed(42)

# ── All Symptoms (377 unique symptoms) ──
ALL_SYMPTOMS = [
    "itching","skin_rash","nodal_skin_eruptions","continuous_sneezing","shivering",
    "chills","joint_pain","stomach_pain","acidity","ulcers_on_tongue",
    "muscle_wasting","vomiting","burning_micturition","spotting_urination","fatigue",
    "weight_gain","anxiety","cold_hands_and_feets","mood_swings","weight_loss",
    "restlessness","lethargy","patches_in_throat","irregular_sugar_level","cough",
    "high_fever","sunken_eyes","breathlessness","sweating","dehydration",
    "indigestion","headache","yellowish_skin","dark_urine","nausea",
    "loss_of_appetite","pain_behind_the_eyes","back_pain","constipation","abdominal_pain",
    "diarrhoea","mild_fever","yellow_urine","yellowing_of_eyes","acute_liver_failure",
    "fluid_overload","swelling_of_stomach","swelled_lymph_nodes","malaise","blurred_and_distorted_vision",
    "phlegm","throat_irritation","redness_of_eyes","sinus_pressure","runny_nose",
    "congestion","chest_pain","weakness_in_limbs","fast_heart_rate","pain_during_bowel_movements",
    "pain_in_anal_region","bloody_stool","irritation_in_anus","neck_pain","dizziness",
    "cramps","bruising","obesity","swollen_legs","swollen_blood_vessels",
    "puffy_face_and_eyes","enlarged_thyroid","brittle_nails","swollen_extremeties","excessive_hunger",
    "extra_marital_contacts","drying_and_tingling_lips","slurred_speech","knee_pain","hip_joint_pain",
    "muscle_weakness","stiff_neck","swelling_joints","movement_stiffness","spinning_movements",
    "loss_of_balance","unsteadiness","weakness_of_one_body_side","loss_of_smell","bladder_discomfort",
    "foul_smell_of_urine","continuous_feel_of_urine","passage_of_gases","internal_itching","toxic_look_typhos",
    "depression","irritability","muscle_pain","altered_sensorium","red_spots_over_body",
    "belly_pain","abnormal_menstruation","dischromic_patches","watering_from_eyes","increased_appetite",
    "polyuria","family_history","mucoid_sputum","rusty_sputum","lack_of_concentration",
    "visual_disturbances","receiving_blood_transfusion","receiving_unsterile_injections","coma","stomach_bleeding",
    "distention_of_abdomen","history_of_alcohol_consumption","blood_in_sputum","prominent_veins_on_calf",
    "palpitations","painful_walking","pus_filled_pimples","blackheads","scurring",
    "skin_peeling","silver_like_dusting","small_dents_in_nails","inflammatory_nails","blister",
    "red_sore_around_nose","yellow_crust_ooze","prognosis","dry_mouth","tingling_sensation",
    "numbness","burning_sensation","difficulty_breathing","wheezing","tightness_in_chest",
    "frequent_urination","excessive_thirst","blurred_vision","slow_healing_wounds","recurring_infections",
    "unexplained_weight_loss","fruity_breath_odor","increased_hunger","dry_skin","darkened_skin",
    "heart_palpitations","tremors","heat_intolerance","protruding_eyes","goiter",
    "hair_loss","cold_intolerance","weight_gain_thyroid","dry_coarse_skin","memory_problems",
    "hoarse_voice","facial_swelling","menstrual_irregularity","infertility","bone_pain",
    "fractures","stooped_posture","loss_of_height","tooth_loss","eye_pain",
    "halos_around_lights","tunnel_vision","peripheral_vision_loss","eye_redness","excessive_tearing",
    "light_sensitivity","double_vision","floaters","flashing_lights","curtain_over_vision",
    "ear_pain","hearing_loss","ear_discharge","ringing_in_ears","vertigo",
    "balance_problems","facial_pain","nasal_congestion","post_nasal_drip","reduced_smell",
    "snoring","daytime_sleepiness","morning_headache","mouth_sores","difficulty_swallowing",
    "voice_changes","neck_lump","blood_in_urine","pelvic_pain","lower_back_pain",
    "testicular_pain","testicular_swelling","breast_lump","breast_pain","nipple_discharge",
    "skin_dimpling","swollen_lymph_nodes_armpit","rectal_bleeding","change_in_bowel_habits",
    "narrow_stools","feeling_of_incomplete_evacuation","abdominal_bloating","early_satiety",
    "jaundice","liver_enlargement","ascites","portal_hypertension","spider_angiomas",
    "palmar_erythema","gynecomastia","easy_bruising","prolonged_bleeding","petechiae",
    "splenomegaly","bone_marrow_failure","night_sweats","unexplained_fever","painless_swelling",
    "persistent_cough","blood_tinged_sputum","finger_clubbing","pleural_effusion",
    "hemoptysis","chronic_cough","barrel_chest","pursed_lip_breathing","use_of_accessory_muscles",
    "cyanosis","orthopnea","paroxysmal_nocturnal_dyspnea","peripheral_edema","jugular_venous_distension",
    "s3_heart_sound","rapid_weight_gain","exercise_intolerance","syncope","claudication",
    "rest_pain","non_healing_ulcers","gangrene","absent_pulses","cold_extremities",
    "pallor","raynauds_phenomenon","digital_ulcers","calcinosis","telangiectasia",
    "dysphagia_scleroderma","skin_tightening","proximal_muscle_weakness","heliotrope_rash",
    "gottron_papules","mechanic_hands","butterfly_rash","photosensitivity","oral_ulcers",
    "serositis","renal_involvement","hematologic_abnormalities","morning_stiffness",
    "symmetric_joint_swelling","rheumatoid_nodules","swan_neck_deformity","boutonniere_deformity",
    "sacroiliac_pain","reduced_spinal_mobility","enthesitis","dactylitis","uveitis",
    "skin_plaques","nail_pitting","pencil_in_cup_deformity","tophi","podagra",
    "joint_aspiration_crystals","renal_stones_gout","cognitive_decline","memory_loss",
    "language_difficulties","visuospatial_problems","personality_changes","wandering",
    "agitation","hallucinations_dementia","resting_tremor","bradykinesia","rigidity",
    "postural_instability","shuffling_gait","micrographia","masked_face","freezing_of_gait",
    "seizures","aura","postictal_confusion","tongue_biting","incontinence_seizure",
    "automatisms","focal_weakness","sensory_changes","optic_neuritis","lhermitte_sign",
    "uhthoff_phenomenon","intention_tremor","scanning_speech","nystagmus","internuclear_ophthalmoplegia",
    "progressive_weakness","fasciculations","muscle_atrophy","dysphagia_neuro","dysarthria",
    "emotional_lability","foot_drop","hyperreflexia","spasticity","respiratory_failure",
    "sudden_severe_headache","worst_headache_of_life","nuchal_rigidity","photophobia_meningeal",
    "altered_consciousness","focal_neurological_deficits","papilledema","projectile_vomiting",
    "cushing_triad","scalp_tenderness","jaw_claudication","vision_loss_temporal",
    "polymyalgia","elevated_esr","aortic_involvement","epigastric_pain","meal_related_pain",
    "hematemesis","melena","coffee_ground_emesis","gnawing_hunger","acid_reflux",
    "regurgitation","water_brash","nocturnal_symptoms","chronic_heartburn",
    "right_upper_quadrant_pain","murphy_sign","biliary_colic","fat_intolerance",
    "clay_colored_stools","gallstone_pancreatitis","epigastric_radiating_to_back",
    "severe_abdominal_pain","lipase_elevation","steatorrhea","pancreatic_calcifications",
    "right_lower_quadrant_pain","rebound_tenderness","mcburney_point","migration_of_pain",
    "rovsing_sign","left_lower_quadrant_pain","diverticular_bleeding","fever_diverticulitis",
    "bloody_diarrhea","tenesmus","urgency","extraintestinal_manifestations_ibd",
    "skip_lesions","continuous_inflammation","perianal_disease","fistulas","strictures",
    "malabsorption","celiac_antibodies","villous_atrophy","dermatitis_herpetiformis",
    "growth_failure","polydipsia","polyuria_diabetes","polyphagia","diabetic_ketoacidosis",
    "hypoglycemia_symptoms","diabetic_neuropathy","diabetic_retinopathy","diabetic_nephropathy",
    "acromegalic_features","enlarged_hands_feet","coarsened_facial_features","visual_field_defects",
    "moon_face","central_obesity","purple_striae","buffalo_hump","hirsutism",
    "skin_darkening_addisons","salt_craving","orthostatic_hypotension_addisons","adrenal_crisis",
    "flank_pain","costovertebral_angle_tenderness","dysuria","urinary_frequency",
    "urinary_urgency","suprapubic_pain","cloudy_urine","strong_urine_odor",
    "urinary_retention","overflow_incontinence","weak_stream","hesitancy",
    "post_void_dribbling","nocturia","incomplete_emptying","stress_incontinence",
    "urge_incontinence","mixed_incontinence","functional_incontinence"
]

# ── Diseases with their associated symptom indices ──
# Each disease maps to a list of symptom names from ALL_SYMPTOMS
DISEASES = {
    "Fungal infection": ["itching","skin_rash","nodal_skin_eruptions","dischromic_patches"],
    "Allergy": ["continuous_sneezing","shivering","chills","watering_from_eyes","runny_nose","congestion"],
    "GERD": ["stomach_pain","acidity","ulcers_on_tongue","vomiting","cough","chest_pain","acid_reflux","regurgitation"],
    "Chronic Cholestasis": ["itching","vomiting","yellowish_skin","nausea","loss_of_appetite","abdominal_pain","yellowing_of_eyes"],
    "Drug Reaction": ["itching","skin_rash","stomach_pain","burning_micturition","spotting_urination"],
    "Peptic Ulcer Disease": ["vomiting","loss_of_appetite","abdominal_pain","passage_of_gases","internal_itching","epigastric_pain","meal_related_pain"],
    "AIDS": ["muscle_wasting","patches_in_throat","high_fever","extra_marital_contacts","weight_loss"],
    "Diabetes Type 1": ["fatigue","weight_loss","excessive_hunger","excessive_thirst","frequent_urination","blurred_vision","polydipsia","polyphagia"],
    "Diabetes Type 2": ["fatigue","weight_gain","excessive_thirst","frequent_urination","blurred_vision","slow_healing_wounds","recurring_infections","darkened_skin"],
    "Gastroenteritis": ["vomiting","diarrhoea","dehydration","abdominal_pain","nausea","mild_fever"],
    "Bronchial Asthma": ["fatigue","cough","breathlessness","high_fever","difficulty_breathing","wheezing","tightness_in_chest"],
    "Hypertension": ["headache","chest_pain","dizziness","fatigue","breathlessness","blurred_vision"],
    "Migraine": ["headache","pain_behind_the_eyes","nausea","vomiting","blurred_and_distorted_vision","visual_disturbances","light_sensitivity"],
    "Cervical Spondylosis": ["back_pain","neck_pain","dizziness","weakness_in_limbs","stiff_neck"],
    "Paralysis (Brain Hemorrhage)": ["vomiting","headache","weakness_of_one_body_side","altered_sensorium","slurred_speech"],
    "Jaundice": ["itching","vomiting","fatigue","weight_loss","high_fever","yellowish_skin","dark_urine","abdominal_pain","yellowing_of_eyes","jaundice"],
    "Malaria": ["chills","vomiting","high_fever","sweating","headache","nausea","muscle_pain"],
    "Chicken Pox": ["itching","skin_rash","fatigue","high_fever","headache","lethargy","red_spots_over_body","blister"],
    "Dengue": ["skin_rash","chills","joint_pain","vomiting","fatigue","high_fever","headache","nausea","loss_of_appetite","pain_behind_the_eyes","back_pain","muscle_pain","red_spots_over_body"],
    "Typhoid": ["chills","vomiting","fatigue","high_fever","headache","nausea","constipation","abdominal_pain","diarrhoea","toxic_look_typhos","belly_pain"],
    "Hepatitis A": ["joint_pain","vomiting","yellowish_skin","dark_urine","nausea","loss_of_appetite","abdominal_pain","diarrhoea","mild_fever","yellowing_of_eyes","muscle_pain"],
    "Hepatitis B": ["itching","fatigue","lethargy","yellowish_skin","dark_urine","loss_of_appetite","abdominal_pain","yellow_urine","yellowing_of_eyes","malaise","receiving_blood_transfusion"],
    "Hepatitis C": ["fatigue","yellowish_skin","nausea","loss_of_appetite","yellowing_of_eyes","family_history"],
    "Hepatitis D": ["joint_pain","vomiting","fatigue","yellowish_skin","dark_urine","nausea","loss_of_appetite","abdominal_pain","yellowing_of_eyes"],
    "Hepatitis E": ["joint_pain","vomiting","fatigue","high_fever","yellowish_skin","dark_urine","nausea","loss_of_appetite","abdominal_pain","yellowing_of_eyes","acute_liver_failure","coma","stomach_bleeding"],
    "Alcoholic Hepatitis": ["vomiting","yellowish_skin","abdominal_pain","swelling_of_stomach","distention_of_abdomen","history_of_alcohol_consumption","fluid_overload","yellowing_of_eyes"],
    "Tuberculosis": ["chills","vomiting","fatigue","weight_loss","cough","high_fever","breathlessness","sweating","loss_of_appetite","mild_fever","phlegm","chest_pain","blood_in_sputum","night_sweats"],
    "Common Cold": ["continuous_sneezing","chills","fatigue","cough","high_fever","headache","runny_nose","congestion","throat_irritation","mild_fever","phlegm","sinus_pressure"],
    "Pneumonia": ["chills","fatigue","cough","high_fever","breathlessness","sweating","chest_pain","phlegm","fast_heart_rate","rusty_sputum","malaise"],
    "Dimorphic Hemorrhoids": ["constipation","pain_during_bowel_movements","pain_in_anal_region","bloody_stool","irritation_in_anus"],
    "Heart Attack": ["vomiting","breathlessness","sweating","chest_pain","dizziness","palpitations","anxiety","nausea"],
    "Varicose Veins": ["fatigue","cramps","bruising","obesity","swollen_legs","swollen_blood_vessels","prominent_veins_on_calf"],
    "Hypothyroidism": ["fatigue","weight_gain","cold_hands_and_feets","mood_swings","lethargy","puffy_face_and_eyes","enlarged_thyroid","brittle_nails","cold_intolerance","weight_gain_thyroid","dry_coarse_skin","memory_problems"],
    "Hyperthyroidism": ["fatigue","weight_loss","mood_swings","fast_heart_rate","sweating","excessive_hunger","dizziness","heart_palpitations","tremors","heat_intolerance","protruding_eyes","goiter","hair_loss"],
    "Hypoglycemia": ["vomiting","fatigue","anxiety","sweating","headache","nausea","palpitations","tremors","blurred_vision","dizziness","irritability"],
    "Osteoarthritis": ["joint_pain","knee_pain","hip_joint_pain","neck_pain","back_pain","swelling_joints","movement_stiffness","muscle_weakness"],
    "Arthritis": ["joint_pain","muscle_weakness","stiff_neck","swelling_joints","movement_stiffness","morning_stiffness","symmetric_joint_swelling"],
    "Vertigo": ["vomiting","headache","nausea","spinning_movements","loss_of_balance","unsteadiness","vertigo"],
    "Acne": ["skin_rash","pus_filled_pimples","blackheads","scurring"],
    "Urinary Tract Infection": ["burning_micturition","bladder_discomfort","foul_smell_of_urine","continuous_feel_of_urine","dysuria","urinary_frequency","urinary_urgency","suprapubic_pain"],
    "Psoriasis": ["itching","skin_rash","joint_pain","skin_peeling","silver_like_dusting","small_dents_in_nails","inflammatory_nails","skin_plaques","nail_pitting"],
    "Impetigo": ["itching","skin_rash","high_fever","blister","red_sore_around_nose","yellow_crust_ooze"],
    "Chronic Kidney Disease": ["fatigue","weight_loss","nausea","loss_of_appetite","swollen_legs","frequent_urination","blood_in_urine","peripheral_edema","easy_bruising"],
    "Anemia": ["fatigue","weight_loss","breathlessness","dizziness","headache","cold_hands_and_feets","pallor","fast_heart_rate","weakness_in_limbs"],
    "Stroke": ["headache","vomiting","weakness_of_one_body_side","slurred_speech","dizziness","blurred_vision","altered_consciousness","focal_neurological_deficits"],
    "Epilepsy": ["headache","dizziness","seizures","aura","postictal_confusion","tongue_biting","incontinence_seizure","automatisms"],
    "Parkinson Disease": ["tremors","muscle_weakness","movement_stiffness","resting_tremor","bradykinesia","rigidity","postural_instability","shuffling_gait","micrographia","masked_face"],
    "Alzheimer Disease": ["depression","irritability","memory_loss","cognitive_decline","language_difficulties","visuospatial_problems","personality_changes","wandering","agitation"],
    "Multiple Sclerosis": ["fatigue","muscle_weakness","numbness","tingling_sensation","blurred_vision","dizziness","optic_neuritis","lhermitte_sign","intention_tremor","nystagmus"],
    "Meningitis": ["high_fever","headache","stiff_neck","nausea","vomiting","light_sensitivity","altered_consciousness","nuchal_rigidity"],
    "Brain Tumor": ["headache","nausea","vomiting","seizures","blurred_vision","personality_changes","focal_neurological_deficits","papilledema","projectile_vomiting"],
    "Lung Cancer": ["cough","breathlessness","weight_loss","chest_pain","fatigue","blood_tinged_sputum","finger_clubbing","hemoptysis","persistent_cough","night_sweats"],
    "Breast Cancer": ["fatigue","weight_loss","breast_lump","breast_pain","nipple_discharge","skin_dimpling","swollen_lymph_nodes_armpit"],
    "Colorectal Cancer": ["fatigue","weight_loss","abdominal_pain","rectal_bleeding","change_in_bowel_habits","narrow_stools","feeling_of_incomplete_evacuation","abdominal_bloating"],
    "Prostate Cancer": ["fatigue","weight_loss","blood_in_urine","lower_back_pain","weak_stream","hesitancy","nocturia","bone_pain"],
    "Leukemia": ["fatigue","weight_loss","high_fever","night_sweats","easy_bruising","prolonged_bleeding","petechiae","splenomegaly","bone_marrow_failure","recurring_infections"],
    "Lymphoma": ["fatigue","weight_loss","night_sweats","unexplained_fever","painless_swelling","itching","swelled_lymph_nodes"],
    "COPD": ["cough","breathlessness","fatigue","wheezing","chronic_cough","barrel_chest","pursed_lip_breathing","use_of_accessory_muscles","cyanosis"],
    "Heart Failure": ["fatigue","breathlessness","swollen_legs","cough","chest_pain","orthopnea","paroxysmal_nocturnal_dyspnea","peripheral_edema","jugular_venous_distension","rapid_weight_gain","exercise_intolerance"],
    "Peripheral Artery Disease": ["fatigue","claudication","rest_pain","non_healing_ulcers","gangrene","absent_pulses","cold_extremities","pallor"],
    "Rheumatoid Arthritis": ["joint_pain","fatigue","morning_stiffness","symmetric_joint_swelling","rheumatoid_nodules","swan_neck_deformity","boutonniere_deformity","muscle_weakness"],
    "Lupus (SLE)": ["fatigue","joint_pain","skin_rash","butterfly_rash","photosensitivity","oral_ulcers","serositis","renal_involvement","hematologic_abnormalities","hair_loss"],
    "Gout": ["joint_pain","swelling_joints","knee_pain","tophi","podagra","joint_aspiration_crystals","renal_stones_gout","high_fever"],
    "Ankylosing Spondylitis": ["back_pain","sacroiliac_pain","reduced_spinal_mobility","enthesitis","morning_stiffness","fatigue","uveitis"],
    "Psoriatic Arthritis": ["joint_pain","skin_rash","skin_plaques","nail_pitting","pencil_in_cup_deformity","dactylitis","enthesitis","morning_stiffness"],
    "Scleroderma": ["skin_tightening","raynauds_phenomenon","digital_ulcers","calcinosis","telangiectasia","dysphagia_scleroderma","breathlessness","fatigue"],
    "Dermatomyositis": ["proximal_muscle_weakness","heliotrope_rash","gottron_papules","mechanic_hands","fatigue","dysphagia_neuro","muscle_pain"],
    "Glaucoma": ["eye_pain","halos_around_lights","tunnel_vision","peripheral_vision_loss","eye_redness","headache","nausea","blurred_vision"],
    "Cataracts": ["blurred_vision","light_sensitivity","double_vision","halos_around_lights","difficulty_breathing"],
    "Retinal Detachment": ["floaters","flashing_lights","curtain_over_vision","blurred_vision","peripheral_vision_loss"],
    "Otitis Media": ["ear_pain","hearing_loss","ear_discharge","high_fever","irritability"],
    "Tinnitus": ["ringing_in_ears","hearing_loss","dizziness","anxiety","depression","difficulty_breathing"],
    "Sinusitis": ["facial_pain","nasal_congestion","post_nasal_drip","reduced_smell","headache","sinus_pressure","cough","mild_fever"],
    "Sleep Apnea": ["snoring","daytime_sleepiness","morning_headache","fatigue","irritability","obesity","headache"],
    "Oral Cancer": ["mouth_sores","difficulty_swallowing","voice_changes","neck_lump","weight_loss","ear_pain"],
    "Kidney Stones": ["flank_pain","blood_in_urine","nausea","vomiting","dysuria","urinary_frequency","costovertebral_angle_tenderness"],
    "Pyelonephritis": ["high_fever","flank_pain","costovertebral_angle_tenderness","dysuria","urinary_frequency","nausea","vomiting","chills"],
    "BPH": ["urinary_retention","weak_stream","hesitancy","post_void_dribbling","nocturia","incomplete_emptying","frequent_urination"],
    "Appendicitis": ["abdominal_pain","nausea","vomiting","mild_fever","right_lower_quadrant_pain","rebound_tenderness","mcburney_point","migration_of_pain"],
    "Diverticulitis": ["abdominal_pain","mild_fever","left_lower_quadrant_pain","diverticular_bleeding","fever_diverticulitis","change_in_bowel_habits","nausea"],
    "Crohn Disease": ["abdominal_pain","diarrhoea","weight_loss","fatigue","perianal_disease","fistulas","strictures","skip_lesions","extraintestinal_manifestations_ibd"],
    "Ulcerative Colitis": ["bloody_diarrhea","abdominal_pain","tenesmus","urgency","weight_loss","fatigue","continuous_inflammation","extraintestinal_manifestations_ibd"],
    "Celiac Disease": ["diarrhoea","abdominal_bloating","weight_loss","fatigue","malabsorption","dermatitis_herpetiformis","growth_failure","abdominal_pain"],
    "Gallstones": ["right_upper_quadrant_pain","murphy_sign","biliary_colic","fat_intolerance","nausea","vomiting","jaundice","clay_colored_stools"],
    "Pancreatitis": ["severe_abdominal_pain","epigastric_radiating_to_back","nausea","vomiting","lipase_elevation","steatorrhea","weight_loss","fatigue"],
    "Cushing Syndrome": ["moon_face","central_obesity","purple_striae","buffalo_hump","hirsutism","weight_gain","fatigue","muscle_weakness","high_fever"],
    "Addison Disease": ["fatigue","weight_loss","skin_darkening_addisons","salt_craving","orthostatic_hypotension_addisons","nausea","muscle_weakness","adrenal_crisis"],
    "Acromegaly": ["acromegalic_features","enlarged_hands_feet","coarsened_facial_features","visual_field_defects","headache","joint_pain","sweating","fatigue"],
    "Osteoporosis": ["bone_pain","fractures","stooped_posture","loss_of_height","back_pain","tooth_loss"],
    "ALS": ["progressive_weakness","fasciculations","muscle_atrophy","dysphagia_neuro","dysarthria","emotional_lability","foot_drop","hyperreflexia","spasticity","respiratory_failure"],
    "Temporal Arteritis": ["scalp_tenderness","jaw_claudication","vision_loss_temporal","polymyalgia","elevated_esr","headache","aortic_involvement","mild_fever"],
    "Subarachnoid Hemorrhage": ["sudden_severe_headache","worst_headache_of_life","nuchal_rigidity","photophobia_meningeal","altered_consciousness","nausea","vomiting"],
    "Irritable Bowel Syndrome": ["abdominal_pain","abdominal_bloating","diarrhoea","constipation","passage_of_gases","cramps","anxiety","fatigue"],
    "Fibromyalgia": ["muscle_pain","fatigue","depression","anxiety","headache","numbness","tingling_sensation","movement_stiffness","lack_of_concentration"],
    "Chronic Fatigue Syndrome": ["fatigue","muscle_pain","headache","lack_of_concentration","depression","joint_pain","sore_throat","swelled_lymph_nodes"],
    "Sciatica": ["back_pain","hip_joint_pain","weakness_in_limbs","numbness","tingling_sensation","painful_walking","lower_back_pain"],
    "Carpal Tunnel Syndrome": ["numbness","tingling_sensation","muscle_weakness","burning_sensation","joint_pain"],
    "Conjunctivitis": ["redness_of_eyes","eye_redness","excessive_tearing","itching","light_sensitivity","watering_from_eyes"],
    "Tonsillitis": ["throat_irritation","high_fever","difficulty_swallowing","headache","neck_pain","swelled_lymph_nodes","mild_fever"],
    "Bronchitis": ["cough","fatigue","breathlessness","phlegm","chest_pain","mild_fever","wheezing","throat_irritation"],
    "Influenza": ["high_fever","cough","fatigue","headache","muscle_pain","chills","runny_nose","throat_irritation","body_ache"],
    "COVID-19": ["high_fever","cough","fatigue","breathlessness","loss_of_smell","headache","muscle_pain","diarrhoea","chest_pain"],
    "Measles": ["high_fever","skin_rash","cough","runny_nose","redness_of_eyes","red_spots_over_body","light_sensitivity"],
    "Mumps": ["high_fever","headache","muscle_pain","fatigue","loss_of_appetite","swelling_joints","neck_pain"],
    "Rubella": ["mild_fever","skin_rash","joint_pain","swelled_lymph_nodes","headache","runny_nose","redness_of_eyes"],
    "Whooping Cough": ["cough","vomiting","fatigue","breathlessness","runny_nose","mild_fever","congestion"],
    "Diphtheria": ["high_fever","throat_irritation","difficulty_swallowing","neck_pain","swelled_lymph_nodes","breathlessness","hoarse_voice"],
    "Tetanus": ["muscle_pain","stiff_neck","difficulty_swallowing","muscle_weakness","spasticity","sweating","high_fever"],
    "Rabies": ["high_fever","headache","anxiety","difficulty_swallowing","agitation","hallucinations_dementia","muscle_weakness","seizures"],
    "Lyme Disease": ["skin_rash","joint_pain","fatigue","headache","chills","muscle_pain","stiff_neck","swelling_joints"],
    "Sepsis": ["high_fever","chills","fast_heart_rate","breathlessness","altered_consciousness","dizziness","sweating","fatigue"],
    "Endocarditis": ["high_fever","fatigue","chills","night_sweats","muscle_pain","joint_pain","weight_loss","heart_palpitations"],
    "Deep Vein Thrombosis": ["swollen_legs","pain_during_bowel_movements","cramps","prominent_veins_on_calf","swollen_blood_vessels","fatigue"],
    "Pulmonary Embolism": ["breathlessness","chest_pain","cough","fast_heart_rate","dizziness","sweating","anxiety","hemoptysis"],
    "Aortic Aneurysm": ["chest_pain","back_pain","abdominal_pain","dizziness","breathlessness","palpitations"],
    "Atrial Fibrillation": ["palpitations","breathlessness","dizziness","fatigue","chest_pain","fast_heart_rate","syncope","anxiety"],
    "Angina": ["chest_pain","breathlessness","sweating","nausea","dizziness","fatigue","anxiety","pain_behind_the_eyes"],
    "Pericarditis": ["chest_pain","breathlessness","mild_fever","fatigue","cough","palpitations","sweating"],
    "Myocarditis": ["chest_pain","breathlessness","fatigue","palpitations","mild_fever","swollen_legs","dizziness","fast_heart_rate"],
    "Cirrhosis": ["fatigue","jaundice","ascites","portal_hypertension","spider_angiomas","palmar_erythema","gynecomastia","abdominal_pain","weight_loss"],
    "Fatty Liver Disease": ["fatigue","abdominal_pain","weight_loss","nausea","liver_enlargement","yellowish_skin"],
    "Liver Cancer": ["fatigue","weight_loss","abdominal_pain","jaundice","liver_enlargement","ascites","loss_of_appetite","nausea"],
    "Stomach Cancer": ["weight_loss","abdominal_pain","nausea","vomiting","loss_of_appetite","early_satiety","abdominal_bloating","fatigue","melena"],
    "Esophageal Cancer": ["difficulty_swallowing","weight_loss","chest_pain","chronic_cough","hoarse_voice","loss_of_appetite","fatigue"],
    "Pancreatic Cancer": ["weight_loss","abdominal_pain","jaundice","loss_of_appetite","nausea","back_pain","fatigue","dark_urine","clay_colored_stools"],
    "Bladder Cancer": ["blood_in_urine","frequent_urination","dysuria","pelvic_pain","lower_back_pain","fatigue","weight_loss"],
    "Kidney Cancer": ["blood_in_urine","flank_pain","weight_loss","fatigue","high_fever","loss_of_appetite","bone_pain"],
    "Testicular Cancer": ["testicular_pain","testicular_swelling","lower_back_pain","fatigue","weight_loss"],
    "Ovarian Cancer": ["abdominal_bloating","pelvic_pain","early_satiety","fatigue","weight_loss","change_in_bowel_habits","frequent_urination"],
    "Cervical Cancer": ["abnormal_menstruation","pelvic_pain","difficulty_swallowing","weight_loss","fatigue","lower_back_pain","blood_in_urine"],
    "Melanoma": ["skin_rash","itching","nodal_skin_eruptions","dischromic_patches","weight_loss","fatigue","swelled_lymph_nodes"],
    "Thyroid Cancer": ["neck_lump","difficulty_swallowing","hoarse_voice","neck_pain","swelled_lymph_nodes","fatigue"],
    "Myeloma": ["bone_pain","fatigue","weight_loss","recurring_infections","renal_involvement","anemia","fractures"],
    "Sickle Cell Disease": ["fatigue","joint_pain","chest_pain","bone_pain","swollen_extremeties","jaundice","dizziness","splenomegaly"],
    "Hemophilia": ["easy_bruising","prolonged_bleeding","joint_pain","swelling_joints","muscle_pain","blood_in_urine"],
    "Thrombocytopenia": ["easy_bruising","petechiae","prolonged_bleeding","fatigue","splenomegaly","nausea","blood_in_urine"],
    "Polycythemia Vera": ["headache","dizziness","itching","fatigue","blurred_vision","splenomegaly","night_sweats","red_spots_over_body"],
    "Iron Deficiency Anemia": ["fatigue","pallor","breathlessness","dizziness","cold_hands_and_feets","brittle_nails","headache","palpitations"],
    "Vitamin B12 Deficiency": ["fatigue","numbness","tingling_sensation","dizziness","memory_problems","depression","pallor","weakness_in_limbs"],
    "Folate Deficiency": ["fatigue","pallor","breathlessness","dizziness","irritability","mouth_sores","depression"],
    "Rickets": ["bone_pain","muscle_weakness","fractures","stooped_posture","growth_failure","fatigue","loss_of_height"],
    "Scurvy": ["fatigue","easy_bruising","bleeding_gums","joint_pain","muscle_pain","skin_rash","tooth_loss"],
    "Pellagra": ["skin_rash","diarrhoea","depression","mouth_sores","fatigue","irritability","cognitive_decline"],
    "Beriberi": ["fatigue","muscle_weakness","numbness","tingling_sensation","breathlessness","swollen_legs","fast_heart_rate","peripheral_edema"],
    "Anxiety Disorder": ["anxiety","restlessness","fatigue","irritability","muscle_pain","lack_of_concentration","palpitations","sweating","tremors"],
    "Depression": ["depression","fatigue","weight_loss","loss_of_appetite","lack_of_concentration","irritability","mood_swings","headache"],
    "Bipolar Disorder": ["mood_swings","depression","anxiety","irritability","fatigue","lack_of_concentration","restlessness","weight_gain"],
    "Schizophrenia": ["hallucinations_dementia","personality_changes","agitation","depression","lack_of_concentration","fatigue","anxiety"],
    "PTSD": ["anxiety","depression","irritability","fatigue","lack_of_concentration","night_sweats","headache","mood_swings"],
    "OCD": ["anxiety","restlessness","depression","irritability","fatigue","lack_of_concentration","mood_swings"],
    "Eating Disorder (Anorexia)": ["weight_loss","fatigue","dizziness","hair_loss","cold_hands_and_feets","depression","menstrual_irregularity","muscle_weakness"],
    "Eating Disorder (Bulimia)": ["weight_loss","fatigue","depression","tooth_loss","mouth_sores","acid_reflux","dehydration"],
    "Insomnia": ["fatigue","anxiety","depression","headache","irritability","lack_of_concentration","mood_swings","daytime_sleepiness"],
    "Narcolepsy": ["daytime_sleepiness","fatigue","muscle_weakness","hallucinations_dementia","dizziness","depression"],
    "Eczema": ["itching","skin_rash","dry_skin","skin_peeling","redness_of_eyes","blister","burning_sensation"],
    "Rosacea": ["redness_of_eyes","skin_rash","burning_sensation","dry_skin","eye_redness","pus_filled_pimples"],
    "Vitiligo": ["dischromic_patches","skin_rash","itching","depression","light_sensitivity"],
    "Alopecia": ["hair_loss","itching","depression","anxiety","stress_incontinence"],
    "Contact Dermatitis": ["itching","skin_rash","burning_sensation","blister","skin_peeling","redness_of_eyes"],
    "Hives (Urticaria)": ["itching","skin_rash","swelling_joints","breathlessness","anxiety","burning_sensation"],
    "Shingles": ["skin_rash","burning_sensation","blister","fatigue","headache","high_fever","tingling_sensation","numbness"],
    "Herpes Simplex": ["skin_rash","blister","burning_sensation","itching","mild_fever","fatigue","tingling_sensation"],
    "Warts": ["skin_rash","nodal_skin_eruptions","itching","skin_peeling"],
    "Ringworm": ["itching","skin_rash","nodal_skin_eruptions","dischromic_patches","red_spots_over_body"],
    "Cellulitis": ["skin_rash","high_fever","swelling_joints","burning_sensation","redness_of_eyes","fatigue","chills"],
    "Abscess": ["high_fever","swelling_joints","burning_sensation","fatigue","chills","pus_filled_pimples","skin_rash"],
    "Gangrene Disease": ["non_healing_ulcers","gangrene","cold_extremities","numbness","skin_rash","fatigue","high_fever"],
    "Plantar Fasciitis": ["painful_walking","hip_joint_pain","fatigue","burning_sensation","movement_stiffness"],
    "Tennis Elbow": ["joint_pain","muscle_weakness","burning_sensation","movement_stiffness","swelling_joints"],
    "Rotator Cuff Injury": ["joint_pain","muscle_weakness","movement_stiffness","neck_pain","back_pain"],
    "Frozen Shoulder": ["joint_pain","movement_stiffness","muscle_weakness","neck_pain","back_pain","swelling_joints"],
    "Bursitis": ["joint_pain","swelling_joints","movement_stiffness","burning_sensation","muscle_weakness"],
    "Tendinitis": ["joint_pain","swelling_joints","movement_stiffness","burning_sensation","muscle_weakness","painful_walking"],
    "Herniated Disc": ["back_pain","numbness","tingling_sensation","muscle_weakness","lower_back_pain","hip_joint_pain","painful_walking"],
    "Spinal Stenosis": ["back_pain","numbness","tingling_sensation","muscle_weakness","lower_back_pain","painful_walking","weakness_in_limbs"],
    "Scoliosis": ["back_pain","movement_stiffness","muscle_weakness","fatigue","breathlessness"],
    "Polymyalgia Rheumatica": ["muscle_pain","morning_stiffness","fatigue","mild_fever","weight_loss","depression","neck_pain"],
    "Sjögren Syndrome": ["dry_mouth","dry_skin","fatigue","joint_pain","redness_of_eyes","difficulty_swallowing","vaginal_dryness"],
    "Raynaud Disease": ["cold_hands_and_feets","raynauds_phenomenon","numbness","tingling_sensation","pallor","digital_ulcers","cold_extremities"],
    "Vasculitis": ["fatigue","weight_loss","muscle_pain","joint_pain","skin_rash","high_fever","night_sweats","numbness"],
    "Sarcoidosis": ["fatigue","cough","breathlessness","skin_rash","joint_pain","blurred_vision","weight_loss","mild_fever"],
    "Amyloidosis": ["fatigue","weight_loss","swollen_legs","numbness","tingling_sensation","breathlessness","enlarged_thyroid","difficulty_swallowing"],
    "Pheochromocytoma": ["high_fever","headache","sweating","palpitations","anxiety","tremors","weight_loss","abdominal_pain"],
    "Hyperparathyroidism": ["bone_pain","fatigue","depression","kidney_stones","nausea","loss_of_appetite","abdominal_pain","muscle_weakness"],
    "Hypoparathyroidism": ["numbness","tingling_sensation","muscle_weakness","seizures","fatigue","depression","dry_skin","brittle_nails"],
    "Pituitary Adenoma": ["headache","visual_field_defects","fatigue","weight_gain","menstrual_irregularity","acromegalic_features"],
    "Polycystic Ovary Syndrome": ["menstrual_irregularity","weight_gain","fatigue","hair_loss","skin_rash","depression","infertility","hirsutism"],
    "Endometriosis": ["abdominal_pain","pelvic_pain","abnormal_menstruation","fatigue","diarrhoea","nausea","infertility","lower_back_pain"],
    "Uterine Fibroids": ["abnormal_menstruation","pelvic_pain","abdominal_bloating","frequent_urination","lower_back_pain","fatigue"],
    "Preeclampsia": ["high_fever","headache","blurred_vision","abdominal_pain","swollen_legs","weight_gain","nausea","palpitations"],
    "Gestational Diabetes": ["excessive_thirst","frequent_urination","fatigue","nausea","blurred_vision","weight_gain","recurring_infections"],
    "Placenta Previa": ["abdominal_pain","bleeding","fatigue","dizziness","lower_back_pain"],
    "Chronic Pancreatitis": ["abdominal_pain","weight_loss","steatorrhea","nausea","vomiting","fatigue","pancreatic_calcifications","back_pain"],
    "Cholangitis": ["high_fever","jaundice","right_upper_quadrant_pain","chills","nausea","vomiting","abdominal_pain"],
    "Achalasia": ["difficulty_swallowing","chest_pain","weight_loss","acid_reflux","regurgitation","cough"],
    "Gastroparesis": ["nausea","vomiting","abdominal_bloating","early_satiety","weight_loss","acid_reflux","abdominal_pain"],
    "Peritonitis": ["severe_abdominal_pain","high_fever","nausea","vomiting","abdominal_bloating","dehydration","fast_heart_rate"],
    "Intestinal Obstruction": ["abdominal_pain","vomiting","constipation","abdominal_bloating","nausea","dehydration"],
    "Hemorrhoids": ["rectal_bleeding","pain_in_anal_region","itching","constipation","bloody_stool","irritation_in_anus"],
    "Anal Fissure": ["pain_in_anal_region","bloody_stool","constipation","burning_sensation","irritation_in_anus"],
    "Colorectal Polyps": ["rectal_bleeding","abdominal_pain","change_in_bowel_habits","constipation","diarrhoea"],
    "Lactose Intolerance": ["abdominal_bloating","diarrhoea","abdominal_pain","nausea","passage_of_gases","cramps"],
    "Food Poisoning": ["nausea","vomiting","diarrhoea","abdominal_pain","high_fever","dehydration","chills","fatigue"],
    "Gastritis": ["abdominal_pain","nausea","vomiting","loss_of_appetite","abdominal_bloating","indigestion","acid_reflux"],
    "Hiatal Hernia": ["acid_reflux","chest_pain","difficulty_swallowing","abdominal_pain","regurgitation","breathlessness"],
    "Cystic Fibrosis": ["cough","breathlessness","fatigue","weight_loss","recurring_infections","steatorrhea","wheezing","growth_failure"],
    "Pulmonary Fibrosis": ["breathlessness","cough","fatigue","finger_clubbing","weight_loss","chest_pain"],
    "Pleural Effusion Disease": ["breathlessness","chest_pain","cough","fatigue","mild_fever","pleural_effusion"],
    "Pneumothorax": ["breathlessness","chest_pain","cough","fast_heart_rate","cyanosis","dizziness"],
    "Sarcoidosis Pulmonary": ["cough","breathlessness","fatigue","chest_pain","night_sweats","weight_loss","skin_rash"],
    "Pulmonary Hypertension": ["breathlessness","fatigue","chest_pain","dizziness","syncope","swollen_legs","palpitations","cyanosis"],
    "Cardiomyopathy": ["breathlessness","fatigue","swollen_legs","palpitations","dizziness","chest_pain","syncope"],
    "Mitral Valve Prolapse": ["palpitations","chest_pain","dizziness","fatigue","breathlessness","anxiety"],
    "Aortic Stenosis": ["breathlessness","chest_pain","syncope","fatigue","dizziness","palpitations","swollen_legs"],
    "Infective Endocarditis": ["high_fever","fatigue","chills","night_sweats","weight_loss","joint_pain","petechiae","heart_palpitations"],
    "Kawasaki Disease": ["high_fever","skin_rash","redness_of_eyes","swollen_extremeties","swelled_lymph_nodes","irritability","mouth_sores"],
    "Henoch-Schönlein Purpura": ["skin_rash","joint_pain","abdominal_pain","blood_in_urine","petechiae","nausea"],
    "Wegener Granulomatosis": ["cough","breathlessness","bloody_stool","joint_pain","fatigue","weight_loss","sinusitis","blood_in_urine"],
    "Polyarteritis Nodosa": ["fatigue","weight_loss","muscle_pain","joint_pain","abdominal_pain","skin_rash","high_fever","numbness"],
    "Takayasu Arteritis": ["fatigue","dizziness","visual_disturbances","headache","chest_pain","claudication","absent_pulses"],
    "Behçet Disease": ["oral_ulcers","skin_rash","joint_pain","eye_redness","uveitis","fatigue","headache"],
}

def generate_dataset():
    """Generate CSV dataset from disease-symptom mappings."""
    # Collect all unique symptoms used
    used_symptoms = set()
    for symptoms in DISEASES.values():
        for s in symptoms:
            if s in ALL_SYMPTOMS:
                used_symptoms.add(s)
    
    symptom_list = sorted(used_symptoms)
    
    rows = []
    for disease, disease_symptoms in DISEASES.items():
        valid_symptoms = [s for s in disease_symptoms if s in symptom_list]
        # Generate multiple samples per disease with slight variation
        n_samples = max(30, 50 - len(valid_symptoms))
        for _ in range(n_samples):
            row = {s: 0 for s in symptom_list}
            # Always include core symptoms (80%+ chance each)
            for s in valid_symptoms:
                if random.random() < 0.85:
                    row[s] = 1
            # Occasionally add noise symptoms (5% chance each)
            for s in symptom_list:
                if s not in valid_symptoms and random.random() < 0.03:
                    row[s] = 1
            # Ensure at least 2 symptoms present
            present = [s for s, v in row.items() if v == 1]
            if len(present) < 2:
                for s in valid_symptoms[:3]:
                    row[s] = 1
            row["prognosis"] = disease
            rows.append(row)
    
    random.shuffle(rows)
    
    output_path = os.path.join(os.path.dirname(__file__), "dataset.csv")
    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=symptom_list + ["prognosis"])
        writer.writeheader()
        writer.writerows(rows)
    
    print(f"Generated {len(rows)} samples for {len(DISEASES)} diseases with {len(symptom_list)} symptoms")
    print(f"Saved to: {output_path}")
    return output_path

if __name__ == "__main__":
    generate_dataset()
